"""
agent.py – LLM-powered standup agent.
Uses shared llm_client and slack_client packages.
"""
import os
import sys
import logging
import httpx
from datetime import datetime, date, timezone
from typing import List, Dict, Optional
from collections import defaultdict

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../../../packages/llm-client"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../../../packages/slack-client"))
from llm_client import call_llm, parse_json_response, active_model
from slack_client import post_message

from .schemas import StandupReport, AssigneeSummary, TicketSnapshot, StandupTriggerRequest

logger = logging.getLogger("standup.agent")

TICKET_SERVICE_URL   = os.getenv("TICKET_SERVICE_URL", "http://localhost:3001")
SLACK_STANDUP_CHANNEL = os.getenv("SLACK_STANDUP_CHANNEL", "#standup")
REQUEST_TIMEOUT       = int(os.getenv("REQUEST_TIMEOUT_SECONDS", "15"))

SYSTEM_PROMPT = """You are an engineering team's standup facilitator.

Read the list of open tickets and produce:
1. A concise standup narrative (2-4 sentences) covering what the team is working on, what's blocked, and what was recently completed.
2. A one-line blurb for each assignee summarising their current work.

Return ONLY valid JSON (no markdown fences, no extra text):
{
  "summary": "<2-4 sentence standup narrative>",
  "assignee_blurbs": {
    "<assignee_name>": "<one-line summary>"
  }
}"""


def _build_prompt(tickets: List[Dict], report_date: date) -> str:
    lines = [f"Standup report for: {report_date.isoformat()}", f"Total tickets: {len(tickets)}", ""]
    for t in tickets:
        lines.append(
            f"[{t.get('ticket_id','?')}] {t.get('title','')} "
            f"| status={t.get('status','?')} | priority={t.get('priority','?')} "
            f"| type={t.get('ticket_type','?')} | assignee={t.get('assignee') or 'unassigned'}"
        )
    return "\n".join(lines)


def _build_slack_blocks(report: StandupReport) -> list:
    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": f"📋 Daily Standup — {report.report_date.strftime('%A, %B %d %Y')}", "emoji": True}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": report.summary}},
        {"type": "divider"},
        {"type": "section", "fields": [
            {"type": "mrkdwn", "text": f"*🟡 Open:*\n{report.open_count}"},
            {"type": "mrkdwn", "text": f"*🔵 In Progress:*\n{report.in_progress_count}"},
            {"type": "mrkdwn", "text": f"*🔴 Blocked:*\n{report.blocked_count}"},
            {"type": "mrkdwn", "text": f"*✅ Done Today:*\n{report.done_today_count}"},
            {"type": "mrkdwn", "text": f"*🚨 Critical:*\n{report.critical_count}"},
        ]},
    ]
    if report.by_assignee:
        blocks.append({"type": "divider"})
        for entry in report.by_assignee[:8]:
            ticket_lines = "\n".join(
                f"  • `{t.ticket_id}` {t.title[:50]} — _{t.status}_"
                for t in entry.tickets[:5]
            )
            blocks.append({"type": "section", "text": {"type": "mrkdwn",
                "text": f"*{entry.assignee}* ({entry.ticket_count} tickets)\n{entry.blurb}\n{ticket_lines}"}})
    blocks.append({"type": "context", "elements": [{"type": "mrkdwn",
        "text": f"_Generated by Autonomous PM · {report.generated_at.strftime('%H:%M UTC')} · {report.model_used}_"}]})
    return blocks


class StandupAgent:
    async def _fetch_all_active_tickets(self) -> List[Dict]:
        all_tickets: List[Dict] = []
        active_statuses = ["Open", "In Progress", "In Review", "Blocked"]
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            for status in active_statuses:
                page = 1
                while True:
                    resp = await client.get(f"{TICKET_SERVICE_URL}/tickets", params={"status": status, "page": page, "page_size": 100})
                    resp.raise_for_status()
                    data = resp.json()
                    tickets = data.get("tickets", [])
                    all_tickets.extend(tickets)
                    if page * 100 >= data.get("total", 0):
                        break
                    page += 1
            # Also grab recent Done tickets
            resp = await client.get(f"{TICKET_SERVICE_URL}/tickets", params={"status": "Done", "page_size": 50})
            if resp.status_code == 200:
                all_tickets.extend(resp.json().get("tickets", []))
        logger.info(f"Fetched {len(all_tickets)} tickets")
        return all_tickets

    async def run(self, request: StandupTriggerRequest) -> StandupReport:
        report_date = request.date_filter or date.today()
        now         = datetime.now(timezone.utc)
        model       = active_model()

        raw_tickets = await self._fetch_all_active_tickets()
        if not raw_tickets:
            report = StandupReport(
                report_date=report_date, generated_at=now,
                total_tickets=0, open_count=0, in_progress_count=0,
                blocked_count=0, done_today_count=0, critical_count=0,
                by_assignee=[], summary="No active tickets today. The board is clear! 🎉",
                model_used=model,
            )
            if request.post_to_slack:
                ch = request.channel or SLACK_STANDUP_CHANNEL
                report.channel_posted = await post_message(ch, report.summary, _build_slack_blocks(report))
            return report

        open_count        = sum(1 for t in raw_tickets if t.get("status") == "Open")
        in_progress_count = sum(1 for t in raw_tickets if t.get("status") == "In Progress")
        blocked_count     = sum(1 for t in raw_tickets if t.get("status") == "Blocked")
        critical_count    = sum(1 for t in raw_tickets if t.get("priority") == "Critical")
        done_today_count  = 0
        for t in raw_tickets:
            if t.get("status") in ("Done", "Closed") and t.get("updated_at"):
                try:
                    upd = datetime.fromisoformat(t["updated_at"].replace("Z", "+00:00"))
                    if upd.date() == report_date:
                        done_today_count += 1
                except Exception:
                    pass

        by_assignee_map: Dict[str, List[Dict]] = defaultdict(list)
        for t in raw_tickets:
            by_assignee_map[t.get("assignee") or "Unassigned"].append(t)

        prompt = _build_prompt(raw_tickets, report_date)
        try:
            raw_llm = await call_llm(prompt, SYSTEM_PROMPT, temperature=0.3)
            parsed  = parse_json_response(raw_llm)
        except Exception as e:
            raise RuntimeError(f"LLM call failed: {e}")

        summary         = parsed.get("summary", "Standup summary unavailable.")
        assignee_blurbs = parsed.get("assignee_blurbs", {})

        assignee_summaries: List[AssigneeSummary] = []
        for assignee, tickets in sorted(by_assignee_map.items()):
            snapshots = []
            for t in tickets:
                try:
                    updated_at = datetime.fromisoformat(t["updated_at"].replace("Z", "+00:00")) if t.get("updated_at") else now
                except Exception:
                    updated_at = now
                snapshots.append(TicketSnapshot(
                    ticket_id=t.get("ticket_id", "?"),
                    title=t.get("title", ""),
                    status=t.get("status", ""),
                    priority=t.get("priority", "Medium"),
                    assignee=t.get("assignee"),
                    ticket_type=t.get("ticket_type", "task"),
                    updated_at=updated_at,
                ))
            assignee_summaries.append(AssigneeSummary(
                assignee=assignee,
                ticket_count=len(tickets),
                tickets=snapshots,
                blurb=assignee_blurbs.get(assignee, f"Working on {len(tickets)} ticket(s)."),
            ))

        assignee_summaries.sort(key=lambda x: x.ticket_count, reverse=True)

        report = StandupReport(
            report_date=report_date, generated_at=now,
            total_tickets=len(raw_tickets), open_count=open_count,
            in_progress_count=in_progress_count, blocked_count=blocked_count,
            done_today_count=done_today_count, critical_count=critical_count,
            by_assignee=assignee_summaries, summary=summary, model_used=model,
        )

        if request.post_to_slack:
            ch = request.channel or SLACK_STANDUP_CHANNEL
            report.channel_posted = await post_message(ch, summary, _build_slack_blocks(report))

        logger.info(f"StandupAgent done. {len(raw_tickets)} tickets, posted={report.channel_posted}")
        return report
